all:
	rm -rf bin/
	mkdir bin
	chmod +x parser_test.py
	chmod +x parser4.py
	chmod +x asm_generator.py
	 cp parser_test.py bin/parser_test.py
	 cp lexer.py bin/lexer.py
	 cp ptg.cpp bin/ptg.cpp
	 cp dtg.cpp bin/dtg.cpp
	 cp dotgen.sh bin/dotgen.sh
	 cp parser4.py bin/parser4.py
	 cp Symbol_Table.py bin/Symbol_Table.py
	 cp ST2.py bin/ST2.py
	 cp ThreeAddrCode.py bin/ThreeAddrCode.py
	 cp asm.py bin/asm.py
	 cp asm_generator.py bin/codegen
	cp *.py bin/
	cp asm_generator.py bin/asm_generator
	cp ptg.cpp bin/ptg.cpp
	cp dtg.cpp bin/dtg.cpp
	cp dotgen.sh bin/dotgen.sh

clean:
	rm -rf bin/
	rm *.pyc
	rm  parser.out parselog.txt parsetab.py
